### ISSUE TITLE
Lint complains about treatment of Anonymous in content.opf

### ISSUE THREAD

**Issue by drgrigg** [johnrambow/henry-adams_democracy#1]
When I run lint I get an error:

`m-073: Anonymous contributor values must be exactly **Anonymous**.`

It references the dc:contributor entry "An Anonymous Volunteer", and its assocated "file-as" property.

**Comment by drgrigg** [comment]
Leave it the way you have it in the colophon, though.

**Comment by johnrambow** [comment]
OK, I changed the value to "Anonymous" in both entries. I think you might have a newer version of Lint, since my version didn't flag this.
