### ISSUE TITLE
Treat final note in Chapter 14 as letter

### ISSUE THREAD

**Issue by drgrigg** [johnrambow/henry-adams_democracy#2]
I think you should treat Sybil's final note as though it were a letter, putting it in a blockquote and giving it the appropriate semantic, eg: `blockquote epub:type="z3998:letter"`

Similarly, I would put the postscript beginning "The bitterest part" in yet another `blockquote epub:type="z3998:letter"` and style the paragraph as `epub:type="z3998:postscript"`.

**Comment by johnrambow** [comment]
OK, thank you. I added the semantics as well as the CSS style for a postscript.
