### ISSUE TITLE
Typogrify makes changes which should be accepted

### ISSUE THREAD

**Issue by drgrigg** [johnrambow/henry-adams_democracy#3]
It's mainly putting in hairspaces and correcting the use of en-dashes, but you should accept them all.

**Comment by johnrambow** [comment]
Thanks -- I reran Typogrify and accepted nearly all. Chapters 5 and 6 quote a character who stammers, so I kept in the nonbreaking hyphen for her stammered words. Example: “I think I could manage if I were a C‑c‑countess. It is such a pretty title!”
